import { Node, Position } from '@xyflow/react';

export const initialNodes = [
  {
    id: 'horizontal-1',
    sourcePosition: Position.Right,
    type: 'input',
    data: { label: 'Spaghetti Bolognese', recipeId: 'spaghetti-bolognese' },
  },
  {
    id: 'horizontal-2',
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    data: { label: 'Chicken Curry', recipeId: 'chicken-curry' },
  },
  {
    id: 'horizontal-3',
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    data: { label: 'Beef Stroganoff', recipeId: 'beef-stroganoff' },
  },
  {
    id: 'horizontal-4',
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    data: { label: 'Vegetable Stir Fry', recipeId: 'vegetable-stir-fry' },
  },
  {
    id: 'horizontal-5',
    sourcePosition: Position.Top,
    targetPosition: Position.Bottom,
    data: { label: 'Fish Tacos', recipeId: 'fish-tacos' },
  },
  {
    id: 'horizontal-6',
    sourcePosition: Position.Bottom,
    targetPosition: Position.Top,
    data: { label: 'Lamb Kebabs', recipeId: 'lamb-kebabs' },
  },
  {
    id: 'horizontal-7',
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    data: { label: 'Pancakes', recipeId: 'pancakes' },
  },
  {
    id: 'horizontal-8',
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
    data: { label: 'Chocolate Cake', recipeId: 'chocolate-cake' },
  },
];

export const steps = [
  { id: 'step-1', description: 'Cook the spaghetti', tips: 'Make sure the water is boiling before adding the spaghetti.' },
  { id: 'step-2', description: 'Prepare the sauce', tips: 'Stir frequently to avoid burning the sauce.' },
  { id: 'step-3', description: 'Combine and serve', tips: 'Mix the spaghetti and sauce thoroughly for even coating.' },
  { id: 'step-4', description: 'Cook the chicken', tips: 'Ensure the chicken is cooked through with no pink inside.' },
  { id: 'step-5', description: 'Prepare the curry sauce', tips: 'Simmer the sauce until it thickens.' },
  { id: 'step-6', description: 'Combine and simmer', tips: 'Let the curry simmer to allow the flavors to meld.' },
  { id: 'step-7', description: 'Cook the beef', tips: 'Brown the beef on all sides for maximum flavor.' },
  { id: 'step-8', description: 'Prepare the sauce', tips: 'Use low heat to prevent the sour cream from curdling.' },
  { id: 'step-9', description: 'Combine and serve over noodles', tips: 'Serve immediately to enjoy the dish at its best.' },
  { id: 'step-10', description: 'Prepare the vegetables', tips: 'Cut the vegetables into uniform pieces for even cooking.' },
  { id: 'step-11', description: 'Stir fry the vegetables', tips: 'Cook on high heat to retain the vegetables\' crunch.' },
  { id: 'step-12', description: 'Add sauce and serve', tips: 'Toss the vegetables in the sauce just before serving.' },
  { id: 'step-13', description: 'Cook the fish', tips: 'Cook the fish until it flakes easily with a fork.' },
  { id: 'step-14', description: 'Prepare the slaw', tips: 'Mix the slaw ingredients thoroughly for even flavor.' },
  { id: 'step-15', description: 'Assemble the tacos', tips: 'Warm the tortillas before assembling the tacos.' },
  { id: 'step-16', description: 'Marinate the lamb', tips: 'Marinate the lamb for at least 2 hours for best flavor.' },
  { id: 'step-17', description: 'Skewer and cook the lamb', tips: 'Cook the lamb on high heat for a nice char.' },
  { id: 'step-18', description: 'Serve with sides', tips: 'Serve the kebabs with fresh vegetables and yogurt sauce.' },
  { id: 'step-19', description: 'Prepare the batter', tips: 'Mix the batter until smooth with no lumps.' },
  { id: 'step-20', description: 'Cook the pancakes', tips: 'Flip the pancakes when bubbles form on the surface.' },
  { id: 'step-21', description: 'Serve with syrup', tips: 'Serve the pancakes warm with your favorite syrup.' },
  { id: 'step-22', description: 'Prepare the batter', tips: 'Ensure the batter is well-mixed and smooth.' },
  { id: 'step-23', description: 'Bake the cake', tips: 'Bake until a toothpick inserted into the center comes out clean.' },
  { id: 'step-24', description: 'Frost and serve', tips: 'Let the cake cool completely before frosting.' },
];

export const recipes = [
  {
    id: 'spaghetti-bolognese',
    name: 'Spaghetti Bolognese',
    ingredients: ['Spaghetti', 'Ground Beef', 'Tomato Sauce', 'Onion', 'Garlic'],
    description: 'A classic Italian pasta dish with a rich, meaty sauce.',
    cookingTime: '45 minutes',
    servings: 4,
    steps: ['step-1', 'step-2', 'step-3'],
  },
  {
    id: 'chicken-curry',
    name: 'Chicken Curry',
    ingredients: ['Chicken', 'Curry Powder', 'Coconut Milk', 'Onion', 'Garlic', 'Ginger'],
    description: 'A flavorful and spicy chicken curry.',
    cookingTime: '60 minutes',
    servings: 4,
    steps: ['step-4', 'step-5', 'step-6'],
  },
  {
    id: 'beef-stroganoff',
    name: 'Beef Stroganoff',
    ingredients: ['Beef', 'Mushrooms', 'Onion', 'Sour Cream', 'Beef Broth'],
    description: 'A creamy and savory beef dish served over noodles.',
    cookingTime: '40 minutes',
    servings: 4,
    steps: ['step-7', 'step-8', 'step-9'],
  },
  {
    id: 'vegetable-stir-fry',
    name: 'Vegetable Stir Fry',
    ingredients: ['Mixed Vegetables', 'Soy Sauce', 'Garlic', 'Ginger', 'Sesame Oil'],
    description: 'A quick and healthy vegetable stir fry.',
    cookingTime: '20 minutes',
    servings: 4,
    steps: ['step-10', 'step-11', 'step-12'],
  },
  {
    id: 'fish-tacos',
    name: 'Fish Tacos',
    ingredients: ['Fish Fillets', 'Tortillas', 'Cabbage', 'Lime', 'Sour Cream'],
    description: 'Delicious fish tacos with a tangy slaw.',
    cookingTime: '30 minutes',
    servings: 4,
    steps: ['step-13', 'step-14', 'step-15'],
  },
  {
    id: 'lamb-kebabs',
    name: 'Lamb Kebabs',
    ingredients: ['Lamb', 'Yogurt', 'Garlic', 'Cumin', 'Paprika'],
    description: 'Flavorful lamb kebabs with a yogurt marinade.',
    cookingTime: '50 minutes',
    servings: 4,
    steps: ['step-16', 'step-17', 'step-18'],
  },
  {
    id: 'pancakes',
    name: 'Pancakes',
    ingredients: ['Flour', 'Milk', 'Eggs', 'Baking Powder', 'Sugar'],
    description: 'Fluffy and delicious pancakes.',
    cookingTime: '20 minutes',
    servings: 4,
    steps: ['step-19', 'step-20', 'step-21'],
  },
  {
    id: 'chocolate-cake',
    name: 'Chocolate Cake',
    ingredients: ['Flour', 'Cocoa Powder', 'Sugar', 'Eggs', 'Butter'],
    description: 'A rich and moist chocolate cake.',
    cookingTime: '60 minutes',
    servings: 8,
    steps: ['step-22', 'step-23', 'step-24'],
  },
];
